# This is a basic workflow to help you get started with Actions

name: Update-Dictionary

# Controls when the action will run. 
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '20 11 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cp data/dic.ja.tsv data/dic.ja.tsv.old
          make web
          git config --global user.email "dqneoo@gmail.com"
          git config --global user.name "Github Action"
          git status
          diff data/dic.ja.tsv data/dic.ja.tsv.old && exit 0
          rm data/dic.ja.tsv.old
          git checkout -b update-dictionary
          git add data
          git commit -m "[Auto commit by Github Action] Update data dir"
          git push -f --set-upstream origin update-dictionary
